SparkEdUAB/SparkEd

.gitignore
config.json
i18n/en.i18n.json
i18n/es.i18n.json
i18n/fr.i18n.json
imports/ui/components/Dashboard/DisplayResource.jsx
imports/ui/components/Dashboard/ManageUnits.jsx
imports/ui/components/content/ViewResourceApp.jsx

Media files were not playing on other devices even on the same network as pointed out by @abnios it was caused by location of the file being the address where it was uploaded from .

Fix media across network

---

CODE_OF_CONDUCT.md

used a template by github for code conduct

---

.deploy/mup.js
config.json
i18n/en.i18n.json
i18n/es.i18n.json
imports/ui/components/Accounts/Register.jsx
imports/ui/components/content/Players/Video.js
package-lock.json
package.json
yarn.lock

Fixed the bug on the view resource page. #13

Fix video updating

---

imports/api/accounts/methods.js
imports/ui/components/Accounts/ManageAccounts.jsx
imports/ui/components/Utilities/Modal/Modal.jsx
imports/ui/components/Utilities/Modal/PasswordEdit.jsx

Added a way for admins to change the password of the user. 
#23

Password edit

---

imports/api/accounts/methods.js
imports/ui/components/Accounts/AccountFunction.js
imports/ui/components/Dashboard/Courses.jsx
imports/ui/components/layouts/ChangePassword.jsx
imports/ui/components/layouts/Header.jsx
imports/ui/components/layouts/UserInfo.jsx
imports/ui/modals/MainModal.jsx

Change password

---

README.md

SPKED-32 #comment updated the readme with information

---

imports/ui/components/Accounts/Login.jsx
imports/ui/components/Accounts/Register.jsx

Fixed this bug #40 
errors were not showing in red

Error message

---

imports/ui/components/layouts/Header.jsx

replaced the list with a div and spans 727ee51 @OlivierJM   
redesigned the notification page to suit best the dark mode

Re design note page

---

imports/ui/components/Dashboard/Feedback.jsx

The feedback page was designed to accomodate the dark mode in a better way #62

redesigned the feedback page

---

CONTRIBUTING.md

To make it easy for people new to contributing, I have added a basic guide

added a contributing guide

---

CHANGELOG.md

Added change log from v1 to v1.6.0

added basic of a change log

---

imports/ui/components/layouts/Header.jsx

added a connection status, so that user can know when they are not longer connected to the internet. 
this solves this issue #58

Server status

---

CONTRIBUTING.md

we are likely to get many opensource contributors, the contributing guide needed to be clear

updated the contributing guide

---

README.md

Added Windows installation instruction in Readme

Added Windows installation instruction

---

README.md

Issue fixes #84 
Added stats blurb in lines 6-7.

Added Stats to the Readme 

---

Dockerfile
launchpad.conf

dockerize 😉

---

README.md

#98 added instructions on how to run the docker image

added instructions on how to run a docker image

---

.dockerignore

updated the .dockerignore file

---

.travis.yml
docker-push

added a docker push file and updated the travis config

---

config.json
imports/ui/components/layouts/ImageSlider.jsx

corrected props requirement in imageSlider

---

imports/api/accounts/methods.js

added a check to make sure the method doesn't proceed when there is no logged in user

fixed the undefined error in the console

---

imports/ui/components/WalkThrough/Setup.jsx
imports/ui/components/layouts/ImageSlider.jsx

Uploading the logo is not required and I thought it would be good to hide it initially and allow the user to show or hide it.

showing and hiding the upload button on setup page

---

imports/ui/components/Accounts/Login.jsx
imports/ui/components/Accounts/ManageAccounts.jsx
imports/ui/components/Accounts/Register.jsx
imports/ui/components/Bookmark/Bookmark.jsx
imports/ui/components/Utilities/Utilities.jsx

- Removed jQuery 
- Cleaned bookmarks
- Cleaned Utilities.jsx
- Added proper colours on toast messages

Remove unnecessary code

---

client/routes.js
imports/ui/components/Search/SearchPage.jsx
imports/ui/components/Search/searchpage.css
imports/ui/components/Utilities/Utilities.jsx
imports/ui/components/layouts/InstitutionDetail.jsx

re-created a search page, fixes this #235 
This goes to its own page, it makes the user just focus on searching rather than anything else.

New searchpage [WIP]

---

.gitignore
config.json
imports/ui/components/Home.jsx
imports/ui/components/Search/SearchPage.jsx
imports/ui/components/Search/searchpage.css
imports/ui/components/Utilities/Utilities.jsx
package-lock.json

remove slider and refactor a few things on the landing page

Remove slider
